<?php require('template/header.phtml') ?>
<?php require('template/sidebar.phtml') ?>
<?php require('template/post-sidebar.phtml') ?>

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="images/slider1.png" alt="">
            <div class="carousel-caption">
                <h3>Brand New Ford Mondeo</h3>
                <p>Perfect for a family and those long drives on the motorway</p>
            </div>
        </div>
        <div class="item">
            <img src="images/slider2.png" alt="">
            <div class="carousel-caption">
                <h3>Brand New and Used Luxury Cars</h3>
                <p>Extensive range of luxury cars to suit all pockets, be it new or used</p>
            </div>
        </div>
        <div class="item">
            <img src="images/slider3.png" alt="">
            <div class="carousel-caption">
                <h3>Great Selection of Small Cars</h3>
                <p>Wide selection of small hatchbacks to choose from, brand new and used</p>
            </div>
        </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>


<div class="row marginT30">
    <?php foreach($view->cars as $car): ?>

    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <div class="thumbnail-img-holder"><img src="images/<?=$car['image']?>" width="100%" alt=""></div>
            <div class="caption">
                <h4><?=$car['make_name'] . " " .$car['model_name']; ?> <span class="pull-right"><?=$car['yearOfReg']?></span></h4>
                <p><?=$car['location_name'] . ' | ' . $car['engine_size'] . " " .  $car['fuelType'] . "<span class='pull-right'>" . $car['mileage'] . " miles</span>";?></p>
                <p>
                    <a href="view-car.php?car-id=<?=$car['id']?>" class="btn btn-primary" role="button">View</a>
                    <?php if(User::check()): ?>
                        <?php $id=$car['id']; if(isset($_SESSION["wishlist"]["$id"])): ?>
                            <a <a href="wishlist.php?remove-from-wishlist=action&id=<?=$car['id']; ?>" role="button" class="btn btn-success" title="Click to remove">Added to Wishlist</a>
                        <?php else: ?>
                            <a href="wishlist.php?add-to-wishlist=action&id=<?=$car['id']; ?>" title="Click to add" class="btn btn-default" role="button">Add to Wishlist</a>
                        <?php endif; ?>
                    <?php endif; ?>
                    <button class="btn btn-danger pull-right" role="button"><?="&pound;" . $car['price']?></button>
                </p>
            </div>
        </div>
    </div>

    <?php endforeach; ?>
</div>





<?php require('template/footer.phtml') ?>
