<?php require('template/header.phtml') ?>
<?php require('template/sidebar.phtml') ?>
<?php require('template/post-sidebar.phtml') ?>

    <div class="login col-md-6 col-md-offset-3 marginT30">
        <h3 class="center-text marginB30"><small>Register to view and manage your account</small></h3>


        <?php if(isset($view->messages)): ?>
            <div class="alert alert-danger" role="alert">

                <?php foreach($view->messages["errors"] as $error): ?>
                    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                    <span class="sr-only">Error:</span>
                    <?php echo $error . "<br>"; ?>
                <?php endforeach?>

            </div>
        <?php endif; ?>

        <form action="" method="post" autocomplete="off">
            <div class="input-group marginB20">
                <span class="input-group-addon">*</span>
                <input class="form-control" type="text" name="name" value="<?php if(isset($view->messages["userInput"]["name"])){ echo $view->messages["userInput"]["name"];}?>" placeholder="Full Name" autocomplete="off">
            </div>

            <div class="input-group marginB20">
                <span class="input-group-addon">*</span>
                <input class="form-control" type="email" name="email" value="<?php if(isset($view->messages["userInput"]["email"])){ echo $view->messages["userInput"]["email"];}?>" placeholder="Email" autocomplete="off">
            </div>

            <div class="input-group marginB20">
                <span class="input-group-addon">*</span>
                <input class="form-control" type="number" name="phone-number" value="<?php if(isset($view->messages["userInput"]["phone-number"])){ echo $view->messages["userInput"]["phone-number"];}?>" placeholder="Phone Number" autocomplete="off">
            </div>

            <div class="input-group marginB20">
                <span class="input-group-addon">*</span>
                <input class="form-control" type="text" name="address" value="<?php if(isset($view->messages["userInput"]["address"])){ echo $view->messages["userInput"]["address"];}?>" placeholder="Address" autocomplete="off">
            </div>

            <div class="input-group marginB20">
                <span class="input-group-addon">*</span>
                <input class="form-control" type="text" name="postcode" value="<?php if(isset($view->messages["userInput"]["postcode"])){ echo $view->messages["userInput"]["postcode"];}?>" placeholder="Postcode" autocomplete="off">
            </div>

            <div class="input-group marginB20">
                <span class="input-group-addon">*</span>
                <input class="form-control" type="password" name="password" value="<?php if(isset($view->messages["userInput"]["password"])){ echo $view->messages["userInput"]["password"];}?>" placeholder="Password" autocomplete="off">
            </div>

            <div class="input-group marginB20">
                <span class="input-group-addon">*</span>
                <input class="form-control" type="password" name="password1" value="<?php if(isset($view->messages["userInput"]["password1"])){ echo $view->messages["userInput"]["password1"];}?>" placeholder="Repeat Password" autocomplete="off">
            </div>

            <div class="btn-group">
                <button type="submit" name="submit-register" class="btn btn-primary">
                    Register  &nbsp;
                    <span class="glyphicon glyphicon-circle-arrow-right"></span>
                </button>
            </div>
        </form>

        <small class="pull-left marginT30  marginB20">Got an account? <a href="login.php" class="">Login</a></small>
        <small class="pull-right marginT30"><a href="register.php" class="">Forgot Password</a></small>
    </div>



<?php require('template/footer.phtml') ?>