
<?php require_once "Models/User.php"; ?>


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="css/bootstrap-theme.min.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">

    <title>Car Supermarket | <?php echo $view->pageTitle; ?></title>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script type="text/javascript">var switchTo5x=true;</script>
    <script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
    <script type="text/javascript">stLight.options({publisher: "ur-dab87539-bdf5-54e4-e2bc-24e74bbfb6a9", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>

</head>

<body role=""document">

    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Car Supermarket</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-left">
              <li class="active"><a href="index.php">Buying <span class="sr-only">(current)</span></a></li>
              <li><a href="add-car.php">Selling</a></li>
              <?php
                  if (isset($_SESSION['wishlist'])) {
                      $total = 0;
                      foreach($_SESSION['wishlist'] as $item) {
                          $total += $item['price'];
                      }
                  }
              if (User::check()): ?>
                  <li>
                  <button onclick="location.href='wishlist.php'" class="auto-margin btn btn-primary" type="button">
                      Wishlist <span class="badge"> <?php if(isset($_SESSION["wishlist"])){ echo count($_SESSION["wishlist"]); } else{ echo 0; } if(count($_SESSION["wishlist"]) == 1){ echo " Car - "; }else{ echo " Cars - ";}?>£<?=$total?></span>
                  </button>
                  </li>
              <?php endif; ?>
          </ul>

            <ul class="nav navbar-nav navbar-right">
                <?php if (!User::check()): ?>
                <li class="active"><a href="login.php">Login</a></li>
                <li><a href="register.php">Register</a></li>
                <?php endif; ?>
                <?php if (User::check()): ?>
                <li class="dropdown active">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span>&nbsp;<?php if(isset($_SESSION['user']['fullname'])){ echo $_SESSION['user']['fullname']; } ?>&nbsp; <span class="caret"></span></a>
                    <ul class="dropdown-menu li-center" role="menu">
                        <li><a href="wishlist.php">View My Wishlist</a></li>
                        <li><a href="my-adverts.php">View My Adverts</a></li>
                        <li class="divider"></li>
                        <li><a href="edit-profile.php">Edit My Profile</a></li>
                    </ul>
                </li>
                <li><a href="logout.php">Logout&nbsp;&nbsp;&nbsp;<span class="glyphicon glyphicon-off"></span></a></li>
                <li>&nbsp;</li>
                <?php endif; ?>
            </ul>
          <form class="navbar-form navbar-right" action="search.php" method="get">
            <input type="text" class="form-control" name="header-search-text" placeholder="Search for cars">
          </form>
        </div>
        </div>
    </nav>

    <div class="container-fluid main-container">





