	<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <?php if(!empty($view->pageHeading)): ?>
            <h1 class="page-header"><?=$view->pageHeading?></h1>
        <?php endif; ?>

        <?php if(isset($view->noticeIndex)): ?>
            <div class="alert alert-success alert-dismissible" role="alert">
                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <strong> Success! </strong> <?=$view->noticeIndex?>
            </div>
        <?php endif; ?>

        <?php if(isset($_GET['noticeIndex'])): ?>
            <div class="alert alert-success alert-dismissible" role="alert">
                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <strong> Success! </strong> <?=$_GET['noticeIndex']?>
            </div>
        <?php endif; ?>