
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="">Search for new & used cars<span class="sr-only">(current)</span></a></li>
          </ul>

          <form action="search.php" method="post" autocomplete="off">
            <div class="input-group marginB20" style="width: 100%">
                <select class="form-control" name="location">
                    <option value="">Select Location</option>
                    <?php foreach($view->locations as $location): ?>
                        <option value="<?php echo $location['location_id']; ?>"  <?php if(isset($view->searchMessages["userInput"]["location"]) && $view->searchMessages["userInput"]["location"] == $location['location_id']){ echo " selected"; } ?>><?php echo $location['location_name']; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>


            <div class="input-group marginB20" style="width: 100%">
                <select class="form-control" name="make" id="" onchange="this.form.submit()">
                    <option value="">Select Make</option>
                    <?php foreach($view->makes as $make): ?>
                        <option value="<?php echo $make['make_id']; ?>"  <?php if(isset($view->searchMessages["userInput"]["make"]) && $view->searchMessages["userInput"]["make"] == $make['make_id']){ echo " selected"; } ?>><?php echo $make['make_name']; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>


            <div class="input-group marginB20" style="width: 100%">
                <select class="form-control" name="model" id="">
                    <option value="">Select Model</option>
                    <?php foreach($view->models as $model): ?>
                        <option value="<?php echo $model['model_id']; ?>"  <?php if(isset($view->searchMessages["userInput"]["model"]) && $view->searchMessages["userInput"]["model"] == $model['model_id']){ echo " selected"; } ?>><?php echo $model['model_name']; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>


            <div class="input-group marginB20" style="width: 100%">
                <select class="form-control" name="min-price">
                    <option value="">Min Price</option>
                    <option value="1000">&pound;1.000</option>
                    <option value="2000">&pound;2.000</option>
                    <option value="3000">&pound;3.000</option>
                    <option value="5000">&pound;5.000</option>
                    <option value="8000">&pound;8.000</option>
                    <option value="10000">&pound;10.000</option>
                    <option value="12000">&pound;12.000</option>
                    <option value="15000">&pound;15.000</option>
                    <option value="20000">&pound;20.000</option>
                    <option value="25000">&pound;25.000</option>
                    <option value="30000">&pound;30.000</option>
                    <option value="40000">&pound;40.000</option>
                    <option value="50000">&pound;50.000</option>
                    <option value="60000">&pound;60.000</option>
                    <option value="70000">&pound;70.000</option>
                    <option value="80000">&pound;80.000</option>
                    <option value="90000">&pound;90.000</option>
                    <option value="100000">&pound;100.000</option>
                </select>
            </div>


            <div class="input-group marginB20" style="width: 100%">
                <select class="form-control" name="max-price">
                  <option value="">Max Price</option>
                  <option value="1000">&pound;1.000</option>
                  <option value="2000">&pound;2.000</option>
                  <option value="3000">&pound;3.000</option>
                  <option value="5000">&pound;5.000</option>
                  <option value="8000">&pound;8.000</option>
                  <option value="10000">&pound;10.000</option>
                  <option value="12000">&pound;12.000</option>
                  <option value="15000">&pound;15.000</option>
                  <option value="20000">&pound;20.000</option>
                  <option value="25000">&pound;25.000</option>
                  <option value="30000">&pound;30.000</option>
                  <option value="40000">&pound;40.000</option>
                  <option value="50000">&pound;50.000</option>
                  <option value="60000">&pound;60.000</option>
                  <option value="70000">&pound;70.000</option>
                  <option value="80000">&pound;80.000</option>
                  <option value="90000">&pound;90.000</option>
                  <option value="100000">&pound;100.000</option>
                </select>
            </div>

              <div class="btn-group" style="width: 100%">
                <button type="submit" name="sidebar-search-submit" class="btn btn-lg btn-primary" style="width: 100%">
                Search Cars  &nbsp;
                <span class="glyphicon glyphicon-circle-arrow-right"></span>
                </button>
              </div>
          </form>

        </div>
        